/* eslint-disable @next/next/no-img-element -- two fixed-size static PNGs from public/;
   next/image would add a loader and a runtime dependency on sharp for no benefit. */

// The mark is the brush photograph, generated by scripts/logo-assets.ts. Two files rather than
// one recoloured by CSS: the ink is ink-primary in each mode, and those are two different hues
// (pale blue / deep teal) - not an inversion of one another, so `filter: invert()` would land on
// neither. Both are 256px and ~25KB.
//
// Both <img> are in the DOM with one hidden per mode, so the mark is correct on FIRST PAINT.
// Choosing the src in JavaScript would mean the pre-paint mode script and React disagreeing for
// a frame, which is a visible flash of the wrong-coloured logo on every load.
export function BrandLogo({ size = 28, className = '' }: { size?: number; className?: string }) {
  const common = 'block object-contain'
  return (
    <>
      <img
        src="/logo-dark.png"
        alt=""
        width={size}
        height={size}
        aria-hidden="true"
        className={`hidden dark:block ${common} ${className}`}
      />
      <img
        src="/logo-light.png"
        alt=""
        width={size}
        height={size}
        aria-hidden="true"
        className={`dark:hidden ${common} ${className}`}
      />
    </>
  )
}

/** Mark + wordmark, linking home. The one place the site's name is spelled. */
export function BrandLockup({ size = 28, text = 'text-base' }: { size?: number; text?: string }) {
  return (
    <a
      href="/"
      className="flex items-center gap-2 no-underline hover:opacity-80 transition-opacity focus-ring rounded-sm"
    >
      <BrandLogo size={size} />
      {/* Arial, like everything else - see tailwind.config.ts. Proxyma's Orbitron cannot spell
          this name: Google publishes it with the `latin` subset only, so every diacritic in
          "Cảm âm Tiêu Dao" would fall back and the wordmark would render in two typefaces. */}
      <span className={`font-brand font-bold text-brand-legible tracking-[0.04em] ${text}`}>
        Cảm âm Tiêu Dao
      </span>
    </a>
  )
}
