"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Heart, X, ChevronUp } from "lucide-react";

export const SUPPORT_TITLE = "Ủng hộ Cảm âm Tiêu Dao";
const BLURB =
  "Cảm âm Tiêu Dao sẽ luôn là một công cụ hoàn toàn miễn phí! Nếu bạn thấy hữu ích, hãy cùng " +
  "mình duy trì dịch vụ và tiếp thêm động lực cho mình ra thêm nhiều bản cảm âm mới nhé.";

/** The event the footer link fires to open the dialog from anywhere on the page. */
export const OPEN_SUPPORT = "camam:open-support";
export const openSupport = () => window.dispatchEvent(new CustomEvent(OPEN_SUPPORT));

/**
 * The blurb and the transfer code.
 *
 * The QR is VECTOR, regenerated by scripts/qr-extract.ts from the payload decoded out of the
 * bank's exported card: 2.8KB instead of 571KB, sharp at any size, and no image request. The
 * script refuses to write it unless the decoded payload passes its own EMVCo checksum and the
 * regenerated code decodes back to the identical string - so this scans to exactly what the
 * bank's own card scanned to.
 *
 * Dark modules on a white panel, in both themes. A QR can be read inverted by some scanners
 * and not others, and a donation that fails silently is worse than one that looks out of place.
 *
 * The account details are text below it rather than pixels inside a picture: a phone scans the
 * code, but someone on a desktop types the number, and typing it needs it selectable.
 */
function SupportBody() {
  return (
    <>
      <p className="text-xs text-ink-caption leading-snug mb-3">{BLURB}</p>
      <div className="bg-white rounded-md p-3">
        {/* eslint-disable-next-line @next/next/no-img-element -- a 2.8KB static SVG */}
        <img src="/qr-ung-ho.svg" alt="Mã QR chuyển khoản Vietcombank" className="w-full block" />
      </div>
      <dl className="mt-3 text-xs text-center">
        <dt className="sr-only">Chủ tài khoản</dt>
        <dd className="font-bold text-ink-primary tracking-wide">LE SY HAU</dd>
        <dt className="sr-only">Số tài khoản</dt>
        <dd className="text-ink-caption tabular-nums select-all">0181003535874</dd>
        <dt className="sr-only">Ngân hàng</dt>
        <dd className="text-ink-disabled">Vietcombank</dd>
      </dl>
    </>
  );
}

/**
 * The card over the result panel.
 *
 * It COLLAPSES rather than closes. Dismissing it outright meant a reader who shut it to see the
 * score behind had no way back short of converting again; collapsed to its title bar it stays
 * one click away and costs a strip of the panel instead of half of it.
 */
export function SupportCard() {
  const [open, setOpen] = useState(true);

  // The footer link opens this one too, when a result is on screen.
  useEffect(() => {
    const onOpen = () => setOpen(true);
    window.addEventListener(OPEN_SUPPORT, onOpen);
    return () => window.removeEventListener(OPEN_SUPPORT, onOpen);
  }, []);

  if (!open) {
    return (
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="absolute bottom-2 right-2 z-20 inline-flex items-center gap-2 rounded-card border border-line
          bg-canvas/95 backdrop-blur-md shadow-card px-3 py-2 text-xs font-bold text-ink-primary
          hover:border-brand-solid transition-colors focus-ring"
      >
        <Heart size={14} className="text-brand-legible" aria-hidden="true" />
        {SUPPORT_TITLE}
        <ChevronUp size={14} className="text-ink-disabled" aria-hidden="true" />
      </button>
    );
  }

  return (
    <aside
      aria-label={SUPPORT_TITLE}
      className="absolute bottom-2 right-2 left-2 sm:left-auto z-20 max-w-xs sm:max-w-none sm:w-64
        mx-auto sm:mx-0 rounded-card border border-line bg-canvas/95 backdrop-blur-md shadow-card-lg p-3"
    >
      <button
        type="button"
        onClick={() => setOpen(false)}
        aria-label="Thu gọn"
        title="Thu gọn"
        className="absolute top-1 right-1 w-7 h-7 rounded-full flex items-center justify-center
          text-ink-disabled hover:bg-ink-caption/10 hover:text-ink-primary transition-colors focus-ring"
      >
        <X size={14} aria-hidden="true" />
      </button>
      <h3 className="text-sm font-bold text-ink-primary pr-6 mb-1">{SUPPORT_TITLE}</h3>
      <SupportBody />
    </aside>
  );
}

/**
 * The same content as a dialog, for the footer link - which has to work whether or not a
 * conversion is on screen, so it cannot rely on the card above being mounted.
 */
export function SupportDialog() {
  const [open, setOpen] = useState(false);
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  useEffect(() => {
    const onOpen = () => setOpen(true);
    window.addEventListener(OPEN_SUPPORT, onOpen);
    return () => window.removeEventListener(OPEN_SUPPORT, onOpen);
  }, []);

  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") setOpen(false); };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [open]);

  if (!open || !mounted) return null;

  // PORTALLED TO <body>, and that is not tidiness - it is the only way this can be centred.
  // The footer carries `.glass`, which sets `backdrop-filter`, and an element with a
  // backdrop-filter becomes the containing block for every `position: fixed` descendant. Left
  // in place, `fixed inset-0` resolved against the FOOTER: the dialog opened below the fold,
  // off the bottom of the page.
  return createPortal(
    <div
      role="presentation"
      onClick={() => setOpen(false)}
      className="fixed inset-0 z-[70] bg-mono-950/70 backdrop-blur-sm grid place-items-center p-6"
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-label={SUPPORT_TITLE}
        onClick={(e) => e.stopPropagation()}
        className="relative w-full max-w-xs rounded-card border border-line bg-canvas shadow-card-lg p-4"
      >
        <button
          type="button"
          onClick={() => setOpen(false)}
          aria-label="Đóng"
          className="absolute top-1 right-1 w-8 h-8 rounded-full flex items-center justify-center
            text-ink-disabled hover:bg-ink-caption/10 hover:text-ink-primary transition-colors focus-ring"
        >
          <X size={16} aria-hidden="true" />
        </button>
        <h2 className="text-base font-bold text-ink-primary pr-8 mb-2">{SUPPORT_TITLE}</h2>
        <SupportBody />
      </div>
    </div>,
    document.body,
  );
}

/** The footer entry. A button, because it opens something rather than going somewhere. */
export function SupportLink({ className }: { className?: string }) {
  return (
    <button type="button" onClick={openSupport} className={className}>
      Ủng hộ Cảm âm Tiêu Dao
    </button>
  );
}
